//
//  File.swift
//  fakeVKapp
//
//  Created by Evgeny Alekseev on 04.09.2021.
//

import UIKit

var myGroups = [Group]()

var allGroups = [
    Group(name: "Narnia Dimension",
          image: UIImage(named: "group-narnia-dimension")),
    Group(name: "Wasp Universe",
          image: UIImage(named: "group-wasp-universe")),
    Group(name: "Cronenberged Dimension",
          image: UIImage(named: "group-cronenberged-dimension")),
    Group(name: "Dimension C-132",
          image: UIImage(named: "group-dimension-c132")),
    Group(name: "Corn World",
          image: UIImage(named: "group-corn-world")),
    Group(name: "Froopyland",
          image: UIImage(named: "group-froopyland"))
]

var friends = [
    Friend(firstName: "Morty",
           lastName: "Smith",
           origin: .earth,
           avatar: UIImage(named: "morty-avatar"),
           photos: [UIImage(named: "morty-avatar")]),
    Friend(firstName: "Beth",
           lastName: "Smith",
           origin: .earth,
           avatar: UIImage(named: "beth-avatar"),
           photos: [UIImage(named: "morty-avatar")]),
    Friend(firstName: "Summer",
           lastName: "Smith",
           origin: .earth,
           avatar: UIImage(named: "summer-avatar"),
           photos: [UIImage(named: "summer-avatar")]),
    Friend(firstName: "Bird",
           lastName: "Person",
           origin: .birdWorld,
           avatar: UIImage(named: "birdie-avatar"),
           photos: [UIImage(named: "birdie-avatar")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")]),
    Friend(firstName: randomFirstName(),
           lastName: randomLastName(),
           origin: .earth,
           avatar: UIImage(named: "pixel-rick"),
           photos: [UIImage(named: "pixel-rick")])
]
